version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: .
    container_name: backend
    # restart: always
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      JWT_SECRETE: niyosecrete
      API_PORT: 2002
    ports:
      - "2002:2002"
    depends_on:
      - postgres
    networks:
      - backend-network
    volumes:
      - ./:/app
    

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: